"""
Assign geographic transforms/CRS to PASDA/PEMA orthophoto tiles using the stored tile manifest.
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import List

import numpy as np
import rasterio
from rasterio.crs import CRS
from rasterio.transform import from_bounds

import sys
sys.path.append(str(Path(__file__).resolve().parents[1]))
from config import IMAGERY_DIR

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
LOGGER = logging.getLogger("pema-georef")


def load_manifest(manifest_path: Path) -> List[dict]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    data = json.loads(manifest_path.read_text())
    if not isinstance(data, list):
        raise ValueError("Manifest JSON must contain a list of records")
    return data


def georeference_tile(record: dict, overwrite: bool = True) -> None:
    path = Path(record.get("path", ""))
    bbox = record.get("bbox")
    if not path.exists():
        LOGGER.warning("Tile missing: %s", path)
        return
    if not bbox or len(bbox) != 4:
        LOGGER.warning("Invalid bbox for %s: %s", path, bbox)
        return

    min_lon, min_lat, max_lon, max_lat = map(float, bbox)

    with rasterio.open(path) as src:
        data = src.read()
        height = src.height
        width = src.width
        count = src.count
        dtype = src.dtypes[0]

    transform = from_bounds(min_lon, min_lat, max_lon, max_lat, width, height)
    profile = {
        "driver": "GTiff",
        "height": height,
        "width": width,
        "count": count,
        "dtype": dtype,
        "transform": transform,
        "crs": CRS.from_epsg(4326),
        "compress": "lzw",
    }

    dest_path = path if overwrite else path.with_suffix(".geo.tif")
    tmp_path = dest_path.with_suffix(".tmp.tif")

    with rasterio.open(tmp_path, "w", **profile) as dst:
        dst.write(data)

    tmp_path.replace(dest_path)
    LOGGER.info("Georeferenced %s", dest_path.name)


def main() -> None:
    parser = argparse.ArgumentParser(description="Georeference PEMA tiles using manifest bounding boxes")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=IMAGERY_DIR / "pema_tiles_manifest.json",
        help="Path to manifest JSON generated by download_pema_imagery.py",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing TIFFs in place",
    )
    parser.add_argument(
        "--no-overwrite",
        dest="overwrite",
        action="store_false",
        help="Write *.geo.tif copies instead of replacing originals",
    )
    args = parser.parse_args()

    records = load_manifest(args.manifest)
    LOGGER.info("Loaded %d manifest entries", len(records))
    for record in records:
        try:
            georeference_tile(record, overwrite=args.overwrite)
        except Exception as exc:
            LOGGER.exception("Failed to georeference %s: %s", record.get("path"), exc)


if __name__ == "__main__":
    main()
